services:
  postgres:
    image: postgres:15
    container_name: job_warehouse_pg
    environment:
      POSTGRES_DB: job_warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - job_warehouse_pg_data:/var/lib/postgresql/data
volumes:
  job_warehouse_pg_data:
